/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat32;
export const MemberId = IDL.Nat32;
export const MemberStatus = IDL.Variant({
  'active' : IDL.Null,
  'hiatus' : IDL.Null,
  'graduated' : IDL.Null,
});
export const GroupId = IDL.Nat32;
export const InternalMember = IDL.Record({
  'id' : MemberId,
  'bio' : IDL.Text,
  'status' : MemberStatus,
  'birthdate' : IDL.Int,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'photoUrl' : IDL.Text,
  'groupId' : GroupId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InternalGroup = IDL.Record({
  'id' : GroupId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'bannerUrl' : IDL.Text,
});
export const InternalPost = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat32,
  'content' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Nat,
  'isReported' : IDL.Bool,
  'isLive' : IDL.Bool,
  'updatedAt' : IDL.Nat,
  'viewCount' : IDL.Nat32,
  'isVerified' : IDL.Bool,
  'authorPrincipal' : IDL.Principal,
});
export const ThreadId = IDL.Nat32;
export const Category = IDL.Variant({
  'event' : IDL.Null,
  'pergroup' : IDL.Null,
  'membertalk' : IDL.Null,
  'general' : IDL.Null,
});
export const InternalThread = IDL.Record({
  'id' : ThreadId,
  'upvotes' : IDL.Nat32,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Nat,
  'category' : Category,
  'authorPrincipal' : IDL.Principal,
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'kind' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PublicUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'favoriteGroup' : IDL.Opt(GroupId),
  'name' : IDL.Text,
  'activities' : IDL.Vec(Activity),
  'bookmarks' : IDL.Vec(PostId),
  'email' : IDL.Text,
  'avatar' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([PostId], [], []),
  'addComment' : IDL.Func(
      [IDL.Nat32, IDL.Opt(PostId), IDL.Text],
      [IDL.Nat32],
      [],
    ),
  'addMember' : IDL.Func([InternalMember], [MemberId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([InternalGroup], [GroupId], []),
  'createPost' : IDL.Func([InternalPost], [PostId], []),
  'createThread' : IDL.Func([InternalThread], [ThreadId], []),
  'deleteComment' : IDL.Func([IDL.Nat32], [], []),
  'deleteMember' : IDL.Func([MemberId], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'deleteThread' : IDL.Func([ThreadId], [], []),
  'findGroupBySlug' : IDL.Func([IDL.Text], [InternalGroup], ['query']),
  'findGroupBySubstring' : IDL.Func([IDL.Text], [InternalGroup], ['query']),
  'findPostsByHashtag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InternalPost)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [PublicUserProfile], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [PublicUserProfile], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'listGroups' : IDL.Func([], [IDL.Vec(InternalGroup)], ['query']),
  'listLivePosts' : IDL.Func([], [IDL.Vec(InternalPost)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(InternalPost)], ['query']),
  'listThreads' : IDL.Func([], [IDL.Vec(InternalThread)], ['query']),
  'listThreadsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(InternalThread)],
      ['query'],
    ),
  'listUserProfiles' : IDL.Func([], [IDL.Vec(PublicUserProfile)], []),
  'removeBookmark' : IDL.Func([PostId], [], []),
  'saveCallerUserProfile' : IDL.Func([PublicUserProfile], [], []),
  'upvoteThread' : IDL.Func([ThreadId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat32;
  const MemberId = IDL.Nat32;
  const MemberStatus = IDL.Variant({
    'active' : IDL.Null,
    'hiatus' : IDL.Null,
    'graduated' : IDL.Null,
  });
  const GroupId = IDL.Nat32;
  const InternalMember = IDL.Record({
    'id' : MemberId,
    'bio' : IDL.Text,
    'status' : MemberStatus,
    'birthdate' : IDL.Int,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'photoUrl' : IDL.Text,
    'groupId' : GroupId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InternalGroup = IDL.Record({
    'id' : GroupId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'bannerUrl' : IDL.Text,
  });
  const InternalPost = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat32,
    'content' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Nat,
    'isReported' : IDL.Bool,
    'isLive' : IDL.Bool,
    'updatedAt' : IDL.Nat,
    'viewCount' : IDL.Nat32,
    'isVerified' : IDL.Bool,
    'authorPrincipal' : IDL.Principal,
  });
  const ThreadId = IDL.Nat32;
  const Category = IDL.Variant({
    'event' : IDL.Null,
    'pergroup' : IDL.Null,
    'membertalk' : IDL.Null,
    'general' : IDL.Null,
  });
  const InternalThread = IDL.Record({
    'id' : ThreadId,
    'upvotes' : IDL.Nat32,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Nat,
    'category' : Category,
    'authorPrincipal' : IDL.Principal,
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'kind' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PublicUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'favoriteGroup' : IDL.Opt(GroupId),
    'name' : IDL.Text,
    'activities' : IDL.Vec(Activity),
    'bookmarks' : IDL.Vec(PostId),
    'email' : IDL.Text,
    'avatar' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([PostId], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat32, IDL.Opt(PostId), IDL.Text],
        [IDL.Nat32],
        [],
      ),
    'addMember' : IDL.Func([InternalMember], [MemberId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([InternalGroup], [GroupId], []),
    'createPost' : IDL.Func([InternalPost], [PostId], []),
    'createThread' : IDL.Func([InternalThread], [ThreadId], []),
    'deleteComment' : IDL.Func([IDL.Nat32], [], []),
    'deleteMember' : IDL.Func([MemberId], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'deleteThread' : IDL.Func([ThreadId], [], []),
    'findGroupBySlug' : IDL.Func([IDL.Text], [InternalGroup], ['query']),
    'findGroupBySubstring' : IDL.Func([IDL.Text], [InternalGroup], ['query']),
    'findPostsByHashtag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InternalPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [PublicUserProfile], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [PublicUserProfile], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'listGroups' : IDL.Func([], [IDL.Vec(InternalGroup)], ['query']),
    'listLivePosts' : IDL.Func([], [IDL.Vec(InternalPost)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(InternalPost)], ['query']),
    'listThreads' : IDL.Func([], [IDL.Vec(InternalThread)], ['query']),
    'listThreadsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(InternalThread)],
        ['query'],
      ),
    'listUserProfiles' : IDL.Func([], [IDL.Vec(PublicUserProfile)], []),
    'removeBookmark' : IDL.Func([PostId], [], []),
    'saveCallerUserProfile' : IDL.Func([PublicUserProfile], [], []),
    'upvoteThread' : IDL.Func([ThreadId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };