/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'kind' : string,
  'timestamp' : bigint,
}
export type Category = { 'event' : null } |
  { 'pergroup' : null } |
  { 'membertalk' : null } |
  { 'general' : null };
export type ExternalBlob = Uint8Array;
export type GroupId = number;
export interface InternalGroup {
  'id' : GroupId,
  'country' : string,
  'name' : string,
  'createdAt' : bigint,
  'slug' : string,
  'description' : string,
  'bannerUrl' : string,
}
export interface InternalMember {
  'id' : MemberId,
  'bio' : string,
  'status' : MemberStatus,
  'birthdate' : bigint,
  'name' : string,
  'team' : string,
  'photoUrl' : string,
  'groupId' : GroupId,
}
export interface InternalPost {
  'id' : PostId,
  'title' : string,
  'likeCount' : number,
  'content' : string,
  'thumbnailUrl' : string,
  'hashtags' : Array<string>,
  'createdAt' : bigint,
  'isReported' : boolean,
  'isLive' : boolean,
  'updatedAt' : bigint,
  'viewCount' : number,
  'isVerified' : boolean,
  'authorPrincipal' : Principal,
}
export interface InternalThread {
  'id' : ThreadId,
  'upvotes' : number,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'category' : Category,
  'authorPrincipal' : Principal,
}
export type MemberId = number;
export type MemberStatus = { 'active' : null } |
  { 'hiatus' : null } |
  { 'graduated' : null };
export type PostId = number;
export interface PublicUserProfile {
  'bio' : string,
  'principal' : Principal,
  'favoriteGroup' : [] | [GroupId],
  'name' : string,
  'activities' : Array<Activity>,
  'bookmarks' : Uint32Array,
  'email' : string,
  'avatar' : ExternalBlob,
}
export type ThreadId = number;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[PostId], undefined>,
  'addComment' : ActorMethod<[number, [] | [PostId], string], number>,
  'addMember' : ActorMethod<[InternalMember], MemberId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[InternalGroup], GroupId>,
  'createPost' : ActorMethod<[InternalPost], PostId>,
  'createThread' : ActorMethod<[InternalThread], ThreadId>,
  'deleteComment' : ActorMethod<[number], undefined>,
  'deleteMember' : ActorMethod<[MemberId], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'deleteThread' : ActorMethod<[ThreadId], undefined>,
  'findGroupBySlug' : ActorMethod<[string], InternalGroup>,
  'findGroupBySubstring' : ActorMethod<[string], InternalGroup>,
  'findPostsByHashtag' : ActorMethod<[string], Array<InternalPost>>,
  'getCallerUserProfile' : ActorMethod<[], PublicUserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], PublicUserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'listGroups' : ActorMethod<[], Array<InternalGroup>>,
  'listLivePosts' : ActorMethod<[], Array<InternalPost>>,
  'listPosts' : ActorMethod<[], Array<InternalPost>>,
  'listThreads' : ActorMethod<[], Array<InternalThread>>,
  'listThreadsByCategory' : ActorMethod<[Category], Array<InternalThread>>,
  'listUserProfiles' : ActorMethod<[], Array<PublicUserProfile>>,
  'removeBookmark' : ActorMethod<[PostId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PublicUserProfile], undefined>,
  'upvoteThread' : ActorMethod<[ThreadId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];