/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PostId = number;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type MemberId = number;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type GroupId = number;
export interface InternalPost {
    id: PostId;
    title: string;
    likeCount: number;
    content: string;
    thumbnailUrl: string;
    hashtags: Array<string>;
    createdAt: bigint;
    isReported: boolean;
    isLive: boolean;
    updatedAt: bigint;
    viewCount: number;
    isVerified: boolean;
    authorPrincipal: Principal;
}
export type ThreadId = number;
export interface Activity {
    id: string;
    kind: string;
    timestamp: bigint;
}
export interface PublicUserProfile {
    bio: string;
    principal: Principal;
    favoriteGroup?: GroupId;
    name: string;
    activities: Array<Activity>;
    bookmarks: Uint32Array;
    email: string;
    avatar: ExternalBlob;
}
export interface InternalMember {
    id: MemberId;
    bio: string;
    status: MemberStatus;
    birthdate: bigint;
    name: string;
    team: string;
    photoUrl: string;
    groupId: GroupId;
}
export interface InternalGroup {
    id: GroupId;
    country: string;
    name: string;
    createdAt: bigint;
    slug: string;
    description: string;
    bannerUrl: string;
}
export interface InternalThread {
    id: ThreadId;
    upvotes: number;
    title: string;
    content: string;
    createdAt: bigint;
    category: Category;
    authorPrincipal: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    event = "event",
    pergroup = "pergroup",
    membertalk = "membertalk",
    general = "general"
}
export enum MemberStatus {
    active = "active",
    hiatus = "hiatus",
    graduated = "graduated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBookmark(postId: PostId): Promise<void>;
    addComment(parentId: number, postId: PostId | null, content: string): Promise<number>;
    addMember(member: InternalMember): Promise<MemberId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGroup(group: InternalGroup): Promise<GroupId>;
    createPost(post: InternalPost): Promise<PostId>;
    createThread(thread: InternalThread): Promise<ThreadId>;
    deleteComment(commentId: number): Promise<void>;
    deleteMember(memberId: MemberId): Promise<void>;
    deletePost(postId: PostId): Promise<void>;
    deleteThread(threadId: ThreadId): Promise<void>;
    findGroupBySlug(slug: string): Promise<InternalGroup>;
    findGroupBySubstring(substring: string): Promise<InternalGroup>;
    findPostsByHashtag(hashtag: string): Promise<Array<InternalPost>>;
    getCallerUserProfile(): Promise<PublicUserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<PublicUserProfile>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: PostId): Promise<void>;
    listGroups(): Promise<Array<InternalGroup>>;
    listLivePosts(): Promise<Array<InternalPost>>;
    listPosts(): Promise<Array<InternalPost>>;
    listThreads(): Promise<Array<InternalThread>>;
    listThreadsByCategory(category: Category): Promise<Array<InternalThread>>;
    listUserProfiles(): Promise<Array<PublicUserProfile>>;
    removeBookmark(postId: PostId): Promise<void>;
    saveCallerUserProfile(profile: PublicUserProfile): Promise<void>;
    upvoteThread(threadId: ThreadId): Promise<void>;
}
import type { Activity as _Activity, Category as _Category, ExternalBlob as _ExternalBlob, GroupId as _GroupId, InternalMember as _InternalMember, InternalThread as _InternalThread, MemberId as _MemberId, MemberStatus as _MemberStatus, PostId as _PostId, PublicUserProfile as _PublicUserProfile, ThreadId as _ThreadId, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBookmark(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0);
            return result;
        }
    }
    async addComment(arg0: number, arg1: PostId | null, arg2: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addMember(arg0: InternalMember): Promise<MemberId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(to_candid_InternalMember_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(to_candid_InternalMember_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGroup(arg0: InternalGroup): Promise<GroupId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0);
            return result;
        }
    }
    async createPost(arg0: InternalPost): Promise<PostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0);
            return result;
        }
    }
    async createThread(arg0: InternalThread): Promise<ThreadId> {
        if (this.processError) {
            try {
                const result = await this.actor.createThread(to_candid_InternalThread_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThread(to_candid_InternalThread_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteComment(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteMember(arg0: MemberId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deletePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteThread(arg0: ThreadId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThread(arg0);
            return result;
        }
    }
    async findGroupBySlug(arg0: string): Promise<InternalGroup> {
        if (this.processError) {
            try {
                const result = await this.actor.findGroupBySlug(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findGroupBySlug(arg0);
            return result;
        }
    }
    async findGroupBySubstring(arg0: string): Promise<InternalGroup> {
        if (this.processError) {
            try {
                const result = await this.actor.findGroupBySubstring(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findGroupBySubstring(arg0);
            return result;
        }
    }
    async findPostsByHashtag(arg0: string): Promise<Array<InternalPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.findPostsByHashtag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findPostsByHashtag(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<PublicUserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_PublicUserProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_PublicUserProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<PublicUserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_PublicUserProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_PublicUserProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listGroups(): Promise<Array<InternalGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGroups();
            return result;
        }
    }
    async listLivePosts(): Promise<Array<InternalPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLivePosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLivePosts();
            return result;
        }
    }
    async listPosts(): Promise<Array<InternalPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return result;
        }
    }
    async listThreads(): Promise<Array<InternalThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.listThreads();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listThreads();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listThreadsByCategory(arg0: Category): Promise<Array<InternalThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.listThreadsByCategory(to_candid_Category_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listThreadsByCategory(to_candid_Category_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUserProfiles(): Promise<Array<PublicUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserProfiles();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserProfiles();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeBookmark(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: PublicUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_PublicUserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_PublicUserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upvoteThread(arg0: ThreadId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteThread(arg0);
            return result;
        }
    }
}
function from_candid_Category_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InternalThread_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InternalThread): InternalThread {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicUserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): Promise<PublicUserProfile> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GroupId]): GroupId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    favoriteGroup: [] | [_GroupId];
    name: string;
    activities: Array<_Activity>;
    bookmarks: Uint32Array;
    email: string;
    avatar: _ExternalBlob;
}): Promise<{
    bio: string;
    principal: Principal;
    favoriteGroup?: GroupId;
    name: string;
    activities: Array<Activity>;
    bookmarks: Uint32Array;
    email: string;
    avatar: ExternalBlob;
}> {
    return {
        bio: value.bio,
        principal: value.principal,
        favoriteGroup: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.favoriteGroup)),
        name: value.name,
        activities: value.activities,
        bookmarks: value.bookmarks,
        email: value.email,
        avatar: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.avatar)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ThreadId;
    upvotes: number;
    title: string;
    content: string;
    createdAt: bigint;
    category: _Category;
    authorPrincipal: Principal;
}): {
    id: ThreadId;
    upvotes: number;
    title: string;
    content: string;
    createdAt: bigint;
    category: Category;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        upvotes: value.upvotes,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        category: from_candid_Category_n28(_uploadFile, _downloadFile, value.category),
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    event: null;
} | {
    pergroup: null;
} | {
    membertalk: null;
} | {
    general: null;
}): Category {
    return "event" in value ? Category.event : "pergroup" in value ? Category.pergroup : "membertalk" in value ? Category.membertalk : "general" in value ? Category.general : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InternalThread>): Array<InternalThread> {
    return value.map((x)=>from_candid_InternalThread_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicUserProfile>): Promise<Array<PublicUserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PublicUserProfile_n19(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InternalMember_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalMember): _InternalMember {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_InternalThread_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InternalThread): _InternalThread {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_MemberStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): _MemberStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_PublicUserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicUserProfile): Promise<_PublicUserProfile> {
    return await to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostId | null): [] | [_PostId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: MemberId;
    bio: string;
    status: MemberStatus;
    birthdate: bigint;
    name: string;
    team: string;
    photoUrl: string;
    groupId: GroupId;
}): {
    id: _MemberId;
    bio: string;
    status: _MemberStatus;
    birthdate: bigint;
    name: string;
    team: string;
    photoUrl: string;
    groupId: _GroupId;
} {
    return {
        id: value.id,
        bio: value.bio,
        status: to_candid_MemberStatus_n11(_uploadFile, _downloadFile, value.status),
        birthdate: value.birthdate,
        name: value.name,
        team: value.team,
        photoUrl: value.photoUrl,
        groupId: value.groupId
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ThreadId;
    upvotes: number;
    title: string;
    content: string;
    createdAt: bigint;
    category: Category;
    authorPrincipal: Principal;
}): {
    id: _ThreadId;
    upvotes: number;
    title: string;
    content: string;
    createdAt: bigint;
    category: _Category;
    authorPrincipal: Principal;
} {
    return {
        id: value.id,
        upvotes: value.upvotes,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        category: to_candid_Category_n17(_uploadFile, _downloadFile, value.category),
        authorPrincipal: value.authorPrincipal
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    favoriteGroup?: GroupId;
    name: string;
    activities: Array<Activity>;
    bookmarks: Uint32Array;
    email: string;
    avatar: ExternalBlob;
}): Promise<{
    bio: string;
    principal: Principal;
    favoriteGroup: [] | [_GroupId];
    name: string;
    activities: Array<_Activity>;
    bookmarks: Uint32Array;
    email: string;
    avatar: _ExternalBlob;
}> {
    return {
        bio: value.bio,
        principal: value.principal,
        favoriteGroup: value.favoriteGroup ? candid_some(value.favoriteGroup) : candid_none(),
        name: value.name,
        activities: value.activities,
        bookmarks: value.bookmarks,
        email: value.email,
        avatar: await to_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.avatar)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberStatus): {
    active: null;
} | {
    hiatus: null;
} | {
    graduated: null;
} {
    return value == MemberStatus.active ? {
        active: null
    } : value == MemberStatus.hiatus ? {
        hiatus: null
    } : value == MemberStatus.graduated ? {
        graduated: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    event: null;
} | {
    pergroup: null;
} | {
    membertalk: null;
} | {
    general: null;
} {
    return value == Category.event ? {
        event: null
    } : value == Category.pergroup ? {
        pergroup: null
    } : value == Category.membertalk ? {
        membertalk: null
    } : value == Category.general ? {
        general: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
